# 🔥 NUMPY BOOTCAMP - 7 JOURS POUR DEVENIR IMBATTABLE

**Objectif** : Maîtriser NumPy pour la finance quantitative  
**Durée** : 2h/jour pendant 7 jours  
**Date début** : [TA DATE]

---


In [2]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import time

print("✅ Bibliothèques importées avec succès!")
print(f"Version NumPy: {np.__version__}")

✅ Bibliothèques importées avec succès!
Version NumPy: 2.2.6


## JOUR 1 : CRÉATION D'ARRAYS & INDEXING
**Temps estimé** : 1h30  
**Objectif** : Maîtriser la création et manipulation basique

In [26]:

# ============================================================================
# EXERCICE 1 : Création basique
# ============================================================================
print("--- Exercice 1 : Création d'arrays ---")

# TODO: Crée un array avec les nombres de 0 à 9
arr1 = np.arange(10)
print("Array 0-9:", arr1)

# TODO: Crée un array de 10 zéros
arr_zeros = np.zeros(10)
print("Zeros:", arr_zeros)

# TODO: Crée un array de 5 uns
arr_ones = np.ones(10)
print("Ones:", arr_ones)

# TODO: Crée un array avec des nombres de 0 à 1 (100 points équidistants)
arr_linspace = np.linspace(0,1,10)
print("Linspace (5 premiers):", arr_linspace[0:7])

# TODO: Crée un array aléatoire de 1000 nombres suivant une loi normale
arr_random = np.random.randn(1000)
print("Random (moyenne, std):", arr_random.mean(), arr_random.std())

# Implementation des types et shapes : 
a = np.array([1,2])
b = np.array([[1,2]])
c = np.array([[1,2,7] , [3,4,5]])
type(a)
print("shape a : {}\nshape b : {}\nshape c :{}".format(a.shape,b.shape,c.shape))
print(c)
print(f"shape a : {a.shape}\nshape b : {b.shape}\nshape c :{c.shape}")   # La façon la plus propre et moderne pour le print


--- Exercice 1 : Création d'arrays ---
Array 0-9: [0 1 2 3 4 5 6 7 8 9]
Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Linspace (5 premiers): [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667]
Random (moyenne, std): -0.009588576653217665 1.0201800388842128
shape a : (2,)
shape b : (1, 2)
shape c :(2, 3)
[[1 2 7]
 [3 4 5]]
shape a : (2,)
shape b : (1, 2)
shape c :(2, 3)


### 📝 Mes notes Exercice 1
- `arange(n)` crée [0, 1, ..., n-1]
- `linspace(a, b, n)` crée n points équidistants entre a et b
- `randn(n)` suit une loi N(0,1)

In [36]:
# ============================================================================
# EXERCICE 2 : Indexing et Slicing
# ============================================================================
print("--- Exercice 2 : Indexing & Slicing ---")

prices = np.array([100, 102, 98, 105, 103, 107, 104])

# TODO: Extrais le premier prix
first_price = prices[0]
print(f"Premier prix: {first_price}")

# TODO: Extrais le dernier prix
last_price = prices[-1]
print(f"Dernier prix: {last_price}")

# TODO: Extrais les prix du 2ème au 5ème
middle_prices = prices[1:5]
print(f"Prix milieu: {middle_prices}")

# TODO: Calcule les rendements
returns = (prices[1:] - prices[:-1]) / prices[:-1]
print(f"Rendements: {returns}")
print(f"Rendement moyen: {returns.mean():.4%}")       # On multiplie par 100 et on affiche 4 chiffres après la virgule
print(f"Rendement moyen: {returns.mean():.3%}")
print(f"Rendement moyen: {returns.mean():.4}")         # Afficher jusqu'à 4 chiffres dont le premier n'est pas nul
print(f"Rendement moyen: {(returns.mean() + 1):.4}")   # même chose mais pour bien comprendre la différence
print(f"Rendement moyen: {returns.mean():.4f}")  # 4 chiffres après la virgule 





--- Exercice 2 : Indexing & Slicing ---
Premier prix: 100
Dernier prix: 104
Prix milieu: [102  98 105 103]
Rendements: [ 0.02       -0.03921569  0.07142857 -0.01904762  0.03883495 -0.02803738]
Rendement moyen: 0.7327%
Rendement moyen: 0.733%
Rendement moyen: 0.007327
Rendement moyen: 1.007
Rendement moyen: 0.0073


## 🎨 STRUCTURE COMPLÈTE (TEMPLATE) :

Crée un nouveau notebook et copie cette structure :
```
[Cellule 1 - Markdown] : Titre + Intro
[Cellule 2 - Code]     : Imports
[Cellule 3 - Markdown] : # JOUR 1
[Cellule 4 - Code]     : Exercice 1
[Cellule 5 - Markdown] : Notes Exercice 1
[Cellule 6 - Code]     : Exercice 2
[Cellule 7 - Markdown] : Notes Exercice 2
[Cellule 8 - Code]     : Exercice 3
...
[Cellule N - Markdown] : # JOUR 2
[Cellule N+1 - Code]   : Exercice 4
...

In [45]:
# ============================================================================
# EXERCICE 3 : Opérations vectorisées
# ============================================================================
print("\n--- Exercice 3 : Vectorisation (la PUISSANCE de NumPy) ---")

stock_prices = np.array([95, 100, 105, 110, 115])
print(stock_prices)

# TODO: Ajoute 5 à tous les prix (SANS boucle for)
increased_prices = stock_prices + 5 
print(increased_prices)

# TODO: Calcule le carré de chaque prix
squared = np.sqrt(stock_prices)
print(squared)

# TODO: Applique un rendement de 2% à tous les prix
# Formule: prix * 1.02
after_return = stock_prices * 1.02

# Comparaison vitesse : vectorisé vs boucle
print("\n*** DÉMONSTRATION VITESSE ***")
large_array = np.random.randn(1000000)

# Méthode 1 : boucle Python (LENT)
import time
start = time.time()
result_loop = [x**2 for x in large_array]
time_loop = time.time() - start

# Méthode 2 : NumPy vectorisé (RAPIDE)
start = time.time()
result_numpy = large_array ** 2
time_numpy = time.time() - start

# sécurité pour éviter division par zéro
time_numpy = max(time_numpy, 1e-12)

print(f"Boucle Python: {time_loop:.4f}s")
print(f"NumPy vectorisé: {time_numpy:.6f}s")
print(f"NumPy est {time_loop/time_numpy:.0f}x plus rapide!")


print("\n" + "="*70)
print("JOUR 2 : BROADCASTING & OPÉRATIONS MATRICIELLES")
print("="*70)


--- Exercice 3 : Vectorisation (la PUISSANCE de NumPy) ---
[ 95 100 105 110 115]
[100 105 110 115 120]
[ 9.74679434 10.         10.24695077 10.48808848 10.72380529]

*** DÉMONSTRATION VITESSE ***
Boucle Python: 0.1705s
NumPy vectorisé: 0.006989s
NumPy est 24x plus rapide!

JOUR 2 : BROADCASTING & OPÉRATIONS MATRICIELLES


In [53]:
# ============================================================================
# EXERCICE 4 : Broadcasting (LE concept clé)
# ============================================================================
print("\n--- Exercice 4 : Broadcasting ---")

# Spots et strikes pour options
spots = np.array([90, 95, 100, 105, 110])  # Prix spots
strike = 100  # Un seul strike

# TODO: Calcule le payoff d'un call pour chaque spot
# Formule: max(S - K, 0)
call_payoffs = np.max(spots - strike , 0)    # le max prend le max des elements du tableau final
call_payoffs__ = np.maximum(spots - strike , 0) # le maximum prend le maximum element par element et garde le vecteur
print(call_payoffs)
print(call_payoffs__)
print("####################### Tests pour maximum et max ##########################\n")
a = np.max(np.array([101]) - strike , 0)
b = np.maximum(np.array([101]) - strike ,0)
c = np.maximum(np.array([[101]]) - strike ,0)
print(a)
print(b)
print(c)
print("####################### Fin Tests #################################\n")

print("EXEMPLE Broadcasting:")
spots_col = np.array([90, 95, 100, 105, 110]).reshape(-1, 1)  # Colonne
strikes_row = np.array([90, 95, 100, 105, 110])  # Ligne

# Matrice de payoffs : chaque ligne = un spot, chaque colonne = un strike
payoff_matrix = np.maximum(spots_col - strikes_row, 0)
print("\nMatrice de payoffs (Call):")
print("Spots \\ Strikes:", strikes_row)
print(payoff_matrix)

# TODO: Crée la matrice de payoffs pour des puts
# Formule: max(K - S, 0)
put_payoff_matrix = np.maximum(strikes_row - spots_col , 0)
print(put_payoff_matrix)




--- Exercice 4 : Broadcasting ---
10
[ 0  0  0  5 10]
####################### Tests pour maximum et max ##########################

1
[1]
[[1]]
####################### Fin Tests #################################

EXEMPLE Broadcasting:

Matrice de payoffs (Call):
Spots \ Strikes: [ 90  95 100 105 110]
[[ 0  0  0  0  0]
 [ 5  0  0  0  0]
 [10  5  0  0  0]
 [15 10  5  0  0]
 [20 15 10  5  0]]
[[ 0  5 10 15 20]
 [ 0  0  5 10 15]
 [ 0  0  0  5 10]
 [ 0  0  0  0  5]
 [ 0  0  0  0  0]]


1) Attention à la difference entre la fonction np.max et np.maximum 
2) Le broadcasting est l'adaptation automatique de numpy pour les dimensions des tableaux . 

In [55]:
# ============================================================================
# EXERCICE 5 : Opérations sur les axes
# ============================================================================
print("\n--- Exercice 5 : Axes et Réductions ---")

# Simulation de returns pour 5 actions sur 10 jours
np.random.seed(42)
returns_matrix = np.random.randn(10, 5) * 0.02  # 10 jours, 5 actions

print(returns_matrix)
print("Returns matrix shape:", returns_matrix.shape)

# TODO: Calcule le rendement moyen de CHAQUE action (sur les 10 jours)
mean_returns_per_stock = np.mean(returns_matrix , axis = 0)  # Astuce: axis=0
print(mean_returns_per_stock)

# TODO: Calcule le rendement moyen de CHAQUE jour (sur les 5 actions)
mean_returns_per_day = np.mean(returns_matrix , axis = 1)  # Astuce: axis=1
print(mean_returns_per_day)

# TODO: Calcule l'écart-type de chaque action
std_per_stock = np.std(returns_matrix ,axis = 0)
print(std_per_stock)

# TODO: Trouve l'action avec le meilleur rendement moyen
best_stock_index = np.argmax(mean_returns_per_stock)  # Astuce: np.argmax()
print(best_stock_index)

print("\n*** SOLUTION AXES ***")
print("axis=0 → opération sur les lignes (down)")
print("axis=1 → opération sur les colonnes (across)")



--- Exercice 5 : Axes et Réductions ---
[[ 0.00993428 -0.00276529  0.01295377  0.0304606  -0.00468307]
 [-0.00468274  0.03158426  0.01534869 -0.00938949  0.0108512 ]
 [-0.00926835 -0.0093146   0.00483925 -0.0382656  -0.03449836]
 [-0.01124575 -0.02025662  0.00628495 -0.01816048 -0.02824607]
 [ 0.02931298 -0.00451553  0.00135056 -0.02849496 -0.01088765]
 [ 0.00221845 -0.02301987  0.00751396 -0.01201277 -0.00583387]
 [-0.01203413  0.03704556 -0.00026994 -0.02115422  0.0164509 ]
 [-0.02441687  0.00417727 -0.0391934  -0.02656372  0.00393722]
 [ 0.01476933  0.00342737 -0.00231297 -0.00602207 -0.02957044]
 [-0.01439688 -0.00921278  0.02114244  0.00687237 -0.0352608 ]]
Returns matrix shape: (10, 5)
[-0.00198097  0.00071498  0.00276573 -0.01227304 -0.01177409]
[ 0.00918006  0.00874238 -0.01730153 -0.0143248  -0.00264692 -0.00622682
  0.00400763 -0.0164119  -0.00394176 -0.00617113]
[0.01524574 0.01879878 0.01560974 0.01869945 0.01815987]
2

*** SOLUTION AXES ***
axis=0 → opération sur les lign

1) np.mean( M , axis = 0 ) => Considère les lignes de matrices M Et retourne le vecteur moyenne des vecteurs lignes
2) np.mean( M , axis = 1 ) => Même chose mais avec les colonnes
3) np.argmax(v) => retourne l'indice du plus grand nombre dans les elements de v


In [59]:
# ============================================================================
# EXERCICE 6 : Algèbre linéaire (Portfolio theory)
# ============================================================================
print("\n--- Exercice 6 : Linear Algebra pour Finance ---")

# Rendements de 3 actions
returns = np.array([0.05, 0.08, 0.03])

# Poids du portfolio
weights = np.array([0.3, 0.5, 0.2])

# TODO: Calcule le rendement du portfolio
# Formule: sum(w_i * r_i) = w^T * r
portfolio_return = np.dot(returns , weights)  # Astuce: np.dot()    # C'est le produit matriciel 

print(f"\nRendement portfolio: {portfolio_return:.2%}")

# Matrice de covariance (simplifié)
cov_matrix = np.array([
    [0.04, 0.01, 0.02],
    [0.01, 0.09, 0.015],
    [0.02, 0.015, 0.03]
])

# TODO: Calcule la variance du portfolio
# Formule: w^T * Cov * w
portfolio_variance = weights @ cov_matrix @ weights  # Astuce: w.T @ Cov @ w

# TODO: Calcule la volatilité (écart-type)
portfolio_volatility = np.sqrt(portfolio_variance)

print(f"Volatilité portfolio: {portfolio_volatility:.2%}")


print("\n" + "="*70)
print("JOUR 3 : MANIPULATION AVANCÉE & BOOLEAN INDEXING")
print("="*70)



--- Exercice 6 : Linear Algebra pour Finance ---

Rendement portfolio: 6.10%
Volatilité portfolio: 18.89%

JOUR 3 : MANIPULATION AVANCÉE & BOOLEAN INDEXING


REMARQUE HYPER IMPORTANTE :
Le @ et le np.dot sont les produits matriciels et donc les dimensions sont importants .
MAIS pour les arrays de shape (n,) , ils se considèrent comment 1d et peuvent à la fois se comporter comme une ligne ou comme une colonne selon la nécessité . Et donc si v.shape == (n,) alors v == v.T (La transpose ne fait rien !) 

In [ ]:
# ============================================================================
# EXERCICE 7 : Boolean Indexing (SUPER PUISSANT)
# ============================================================================
print("\n--- Exercice 7 : Boolean Indexing ---")

daily_returns = np.array([0.02, -0.01, 0.03, -0.02, 0.01, -0.03, 0.04])

# TODO: Sélectionne seulement les rendements positifs
positive_returns = None  # Astuce: daily_returns[daily_returns > 0]

# TODO: Compte combien de jours sont positifs
num_positive_days = None  # Astuce: np.sum(condition)

# TODO: Remplace tous les rendements négatifs par 0
returns_floored = None  # Astuce: np.where()

# TODO: Trouve les indices des jours où |return| > 2%
large_moves_indices = None  # Astuce: np.where(np.abs(...) > 0.02)

print("\n*** EXEMPLE Boolean Indexing ***")
prices = np.array([95, 102, 98, 105, 103])
# Sélectionne les prix > 100
expensive = prices[prices > 100]
print(f"Prix > 100: {expensive}")


# ============================================================================
# EXERCICE 8 : Reshape et Transpose
# ============================================================================
print("\n--- Exercice 8 : Reshape & Transpose ---")

# Array 1D de 12 éléments
data = np.arange(12)

# TODO: Reshape en matrice 3x4
matrix_3x4 = None

# TODO: Reshape en matrice 4x3
matrix_4x3 = None

# TODO: Transpose la matrice 3x4
transposed = None  # Astuce: .T

# TODO: Flatten (aplatir) la matrice en 1D
flattened = None  # Astuce: .flatten() ou .ravel()

print("\n*** UTILITÉ EN FINANCE ***")
# Prix de 4 actions sur 3 jours
prices_time_series = np.array([
    [100, 50, 200, 75],   # Jour 1
    [102, 48, 205, 78],   # Jour 2
    [101, 52, 198, 76]    # Jour 3
])
print("Prix (jours x actions):")
print(prices_time_series)

# Transpose pour avoir actions x jours
prices_by_stock = prices_time_series.T
print("\nPrix (actions x jours):")
print(prices_by_stock)


print("\n" + "="*70)
print("JOUR 4 : STATISTIQUES & AGRÉGATIONS")
print("="*70)

# ============================================================================
# EXERCICE 9 : Statistiques descriptives
# ============================================================================
print("\n--- Exercice 9 : Statistiques ---")

# Simule 1000 rendements journaliers
np.random.seed(42)
returns_sample = np.random.randn(1000) * 0.02 + 0.0005  # Moyenne 0.05%, vol 2%

# TODO: Calcule la moyenne
mean = None

# TODO: Calcule l'écart-type
std = None

# TODO: Calcule les percentiles 5%, 50%, 95%
percentiles = None  # Astuce: np.percentile(data, [5, 50, 95])

# TODO: Calcule le Sharpe ratio (annualisé)
# Formule: (mean * 252) / (std * sqrt(252))
sharpe = None

# TODO: Calcule le Value-at-Risk à 95% (perte maximale dans 95% des cas)
var_95 = None  # Astuce: c'est le percentile 5%

# TODO: Calcule la skewness (asymétrie)
# Astuce: peut se faire avec scipy, mais essaie de comprendre le concept
from scipy import stats
skewness = stats.skew(returns_sample)

print(f"\n*** ANALYSE DES RENDEMENTS ***")
print(f"Moyenne journalière: {mean:.4%}")
print(f"Volatilité journalière: {std:.4%}")
print(f"Sharpe Ratio (annualisé): {sharpe:.2f}")
print(f"VaR 95%: {var_95:.4%}")
print(f"Skewness: {skewness:.3f}")



In [ ]:
# ============================================================================
# EXERCICE 10 : Rolling windows (crucial pour backtesting)
# ============================================================================
print("\n--- Exercice 10 : Rolling Statistics ---")

prices_series = 100 * np.exp(np.cumsum(np.random.randn(100) * 0.02))

# TODO: Calcule une moyenne mobile sur 10 jours
# Astuce: utilise np.convolve ou une boucle intelligente
window = 10
moving_average = np.convolve(prices_series, np.ones(window)/window, mode='valid')

# TODO: Calcule la volatilité roulante (rolling std) sur 20 jours
# C'est plus complexe, mais essaie !
window = 20
rolling_std = np.array([np.std(prices_series[i:i+window]) 
                        for i in range(len(prices_series) - window + 1)])

print(f"\nPrix initial: {prices_series[0]:.2f}")
print(f"Prix final: {prices_series[-1]:.2f}")
print(f"MA(10) final: {moving_average[-1]:.2f}")


print("\n" + "="*70)
print("JOUR 5 : SIMULATION MONTE CARLO")
print("="*70)

# ============================================================================
# EXERCICE 11 : Simulation de trajectoires (GBM)
# ============================================================================
print("\n--- Exercice 11 : Geometric Brownian Motion ---")

# Paramètres
S0 = 100        # Prix initial
mu = 0.10       # Drift (rendement annuel)
sigma = 0.20    # Volatilité annuelle
T = 1.0         # Horizon (1 an)
n_steps = 252   # Nombre de pas (jours de trading)
n_sims = 1000   # Nombre de simulations

dt = T / n_steps
np.random.seed(42)

# TODO: Simule n_sims trajectoires de prix
# Formule: S_{t+dt} = S_t * exp((mu - 0.5*sigma^2)*dt + sigma*sqrt(dt)*Z)
# Où Z ~ N(0,1)

# Méthode 1 : Boucle (pour comprendre)
paths = np.zeros((n_steps + 1, n_sims))
paths[0] = S0

for t in range(1, n_steps + 1):
    Z = np.random.randn(n_sims)
    paths[t] = paths[t-1] * np.exp((mu - 0.5*sigma**2)*dt + sigma*np.sqrt(dt)*Z)

# TODO: Calcule le prix moyen à maturité
mean_terminal_price = None

# TODO: Calcule l'intervalle de confiance à 95%
conf_interval = None  # Astuce: percentiles 2.5% et 97.5%

print(f"\n*** RÉSULTATS SIMULATION ***")
print(f"Prix moyen à T={T}: {mean_terminal_price:.2f}")
print(f"Intervalle 95%: [{conf_interval[0]:.2f}, {conf_interval[1]:.2f}]")
print(f"Prix théorique: {S0 * np.exp(mu * T):.2f}")

# Visualisation
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(paths[:, :20], alpha=0.5, linewidth=0.8)  # 20 premières trajectoires
plt.axhline(S0, color='red', linestyle='--', label='Prix initial')
plt.xlabel('Jours')
plt.ylabel('Prix')
plt.title('Trajectoires GBM')
plt.legend()
plt.grid(alpha=0.3)

plt.subplot(1, 2, 2)
plt.hist(paths[-1], bins=50, alpha=0.7, edgecolor='black')
plt.axvline(mean_terminal_price, color='red', linestyle='--', label='Moyenne')
plt.xlabel('Prix terminal')
plt.ylabel('Fréquence')
plt.title('Distribution des prix à maturité')
plt.legend()
plt.grid(alpha=0.3)

plt.tight_layout()
plt.savefig('gbm_simulation.png', dpi=150)
print("\nGraphique sauvegardé: gbm_simulation.png")
plt.show()


In [ ]:
# ============================================================================
# EXERCICE 12 : Pricing d'options par Monte Carlo
# ============================================================================
print("\n--- Exercice 12 : Option Pricing Monte Carlo ---")

K = 100  # Strike
r = 0.05  # Taux sans risque

# TODO: Calcule le payoff d'un call européen pour chaque simulation
call_payoffs = None  # Formule: max(S_T - K, 0)

# TODO: Calcule le prix de l'option (espérance actualisée)
call_price_mc = None  # Formule: exp(-r*T) * mean(payoffs)

# TODO: Calcule l'erreur standard
call_std_error = None

# Prix Black-Scholes (pour comparaison)
from scipy.stats import norm
d1 = (np.log(S0/K) + (r + 0.5*sigma**2)*T) / (sigma*np.sqrt(T))
d2 = d1 - sigma*np.sqrt(T)
call_price_bs = S0*norm.cdf(d1) - K*np.exp(-r*T)*norm.cdf(d2)

print(f"\n*** PRICING CALL OPTION (K={K}) ***")
print(f"Prix Monte Carlo: {call_price_mc:.4f} ± {2*call_std_error:.4f}")
print(f"Prix Black-Scholes: {call_price_bs:.4f}")
print(f"Différence: {abs(call_price_mc - call_price_bs):.4f}")


print("\n" + "="*70)
print("JOUR 6 : OPTIMISATION & PORTFOLIO")
print("="*70)

# ============================================================================
# EXERCICE 13 : Frontière efficiente (Markowitz)
# ============================================================================
print("\n--- Exercice 13 : Portfolio Optimization ---")

# 4 actions avec rendements et covariance
np.random.seed(42)
mean_returns = np.array([0.08, 0.12, 0.15, 0.10])  # Rendements annuels
cov_matrix = np.array([
    [0.04, 0.01, 0.02, 0.005],
    [0.01, 0.09, 0.03, 0.01],
    [0.02, 0.03, 0.16, 0.02],
    [0.005, 0.01, 0.02, 0.05]
])

n_assets = len(mean_returns)
n_portfolios = 10000

# TODO: Génère des poids aléatoires pour 10000 portfolios
# Contrainte: somme des poids = 1, tous positifs
results = np.zeros((3, n_portfolios))  # [returns, risk, sharpe]

for i in range(n_portfolios):
    weights = np.random.random(n_assets)
    weights /= np.sum(weights)
    
    # TODO: Calcule le rendement du portfolio
    portfolio_return = None  # weights @ mean_returns
    
    # TODO: Calcule la volatilité du portfolio
    portfolio_std = None  # sqrt(weights @ cov_matrix @ weights)
    
    # TODO: Calcule le Sharpe ratio
    sharpe = portfolio_return / portfolio_std
    
    results[0, i] = portfolio_return
    results[1, i] = portfolio_std
    results[2, i] = sharpe

# Trouve le portfolio optimal (max Sharpe)
max_sharpe_idx = np.argmax(results[2])
optimal_return = results[0, max_sharpe_idx]
optimal_risk = results[1, max_sharpe_idx]

print(f"\n*** PORTFOLIO OPTIMAL ***")
print(f"Rendement: {optimal_return:.2%}")
print(f"Risque: {optimal_risk:.2%}")
print(f"Sharpe Ratio: {results[2, max_sharpe_idx]:.2f}")

# Visualisation
plt.figure(figsize=(10, 6))
scatter = plt.scatter(results[1], results[0], c=results[2], 
                     cmap='viridis', alpha=0.5, s=10)
plt.scatter(optimal_risk, optimal_return, color='red', marker='*', 
           s=500, label='Optimal Portfolio')
plt.colorbar(scatter, label='Sharpe Ratio')
plt.xlabel('Risque (Volatilité)')
plt.ylabel('Rendement')
plt.title('Frontière Efficiente - 10,000 Portfolios')
plt.legend()
plt.grid(alpha=0.3)
plt.savefig('efficient_frontier.png', dpi=150)
print("\nGraphique sauvegardé: efficient_frontier.png")
plt.show()


print("\n" + "="*70)
print("JOUR 7 : PROJET FINAL - BACKTESTER")
print("="*70)


In [ ]:

# ============================================================================
# EXERCICE 14 : Backtesting d'une stratégie
# ============================================================================
print("\n--- Exercice 14 : Simple Moving Average Strategy ---")

# Génère des prix fictifs
np.random.seed(42)
n_days = 500
prices = 100 * np.exp(np.cumsum(np.random.randn(n_days) * 0.015))

# Paramètres stratégie
short_window = 20
long_window = 50

# TODO: Calcule les moyennes mobiles
short_ma = np.convolve(prices, np.ones(short_window)/short_window, mode='valid')
long_ma = np.convolve(prices, np.ones(long_window)/long_window, mode='valid')

# Ajuste les longueurs
prices_aligned = prices[long_window-1:]
short_ma_aligned = short_ma[long_window-short_window:]

# TODO: Génère les signaux de trading
# Signal = 1 si short_ma > long_ma (achat), -1 sinon (vente)
signals = np.where(short_ma_aligned > long_ma, 1, -1)

# TODO: Calcule les rendements de la stratégie
daily_returns = np.diff(prices_aligned) / prices_aligned[:-1]
strategy_returns = signals[:-1] * daily_returns

# TODO: Calcule les performances
cumulative_returns = np.cumprod(1 + strategy_returns) - 1
total_return = cumulative_returns[-1]
sharpe_ratio = np.mean(strategy_returns) / np.std(strategy_returns) * np.sqrt(252)

# Drawdown
cumulative = np.cumprod(1 + strategy_returns)
running_max = np.maximum.accumulate(cumulative)
drawdown = (cumulative - running_max) / running_max
max_drawdown = np.min(drawdown)

print(f"\n*** RÉSULTATS BACKTEST ***")
print(f"Rendement total: {total_return:.2%}")
print(f"Sharpe Ratio: {sharpe_ratio:.2f}")
print(f"Max Drawdown: {max_drawdown:.2%}")
print(f"Nombre de trades: {np.sum(np.abs(np.diff(signals)))}")

# Visualisation
fig, axes = plt.subplots(3, 1, figsize=(12, 10))

# Prix et moyennes mobiles
axes[0].plot(prices_aligned, label='Prix', alpha=0.7)
axes[0].plot(short_ma_aligned, label=f'MA{short_window}', linewidth=2)
axes[0].plot(long_ma, label=f'MA{long_window}', linewidth=2)
axes[0].set_ylabel('Prix')
axes[0].set_title('Prix et Moyennes Mobiles')
axes[0].legend()
axes[0].grid(alpha=0.3)

# Signaux
axes[1].fill_between(range(len(signals)), 0, signals, alpha=0.3, 
                     label='Signal (1=Long, -1=Short)')
axes[1].set_ylabel('Position')
axes[1].set_title('Signaux de Trading')
axes[1].legend()
axes[1].grid(alpha=0.3)

# Equity curve
axes[2].plot(cumulative_returns * 100, label='Stratégie', linewidth=2)
axes[2].axhline(0, color='black', linestyle='--', alpha=0.5)
axes[2].set_xlabel('Jours')
axes[2].set_ylabel('Rendement cumulé (%)')
axes[2].set_title('Performance de la Stratégie')
axes[2].legend()
axes[2].grid(alpha=0.3)

plt.tight_layout()
plt.savefig('backtest_results.png', dpi=150)
print("\nGraphique sauvegardé: backtest_results.png")
plt.show()


print("\n" + "="*70)
print("FÉLICITATIONS ! TU AS TERMINÉ LE BOOTCAMP NUMPY !")
print("="*70)
print("""
PROCHAINES ÉTAPES :
1. Refais tous les exercices de mémoire (sans regarder)
2. Implémente des variations (change les paramètres, les stratégies)
3. Passe au projet Option Pricer que je t'ai donné avant
4. Commence à lire "Python for Finance" de Yves Hilpisch

TU ES MAINTENANT PRÊT À CONQUÉRIR LE MONDE QUANT !

N'oublie pas :
- Code TOUS LES JOURS
- Push sur GitHub CHAQUE SEMAINE
- Implémente des papers dans 2-3 semaines
- Dans 3 mois, tu seras IMBATTABLE

MAINTENANT, AU TRAVAIL ! 💪🔥
""")